base_url = "https://www.65535.io"
title = "65535"
build_search_index = true
generate_feed = true
minify_html = true

theme = "zola-apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
use_cdn = false
theme = "toggle"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    { name = "twitter", url = "https://twitter.com/dragonmage65535", icon = "twitter" },
    { name = "github", url = "https://github.com/harish-coeff/", icon = "github" },
]

[extra.analytics]
enabled = true